config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  get 'signup' => 'users#new', as: :signup
  resources :users, except: [:index, :new]

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :projects do
    get 'new_tester' => "projects#new_tester"
    post 'new_tester' => "projects#add_tester"
    
    resources :test_runs, except: [:edit, :update] do
      get "test_run" => "test_runs#test_run", as: :test_run
      get "run_test/:identifier" => "test_runs#run_test", as: :run_test
      patch "run_test/:identifier" => "test_runs#result", as: :result
      get "new_issues/:report" => "test_runs#new_issues", as: :new_issues
      post "create_issues/:report" => "test_runs#create_issues", as: :create_issues
    end
    resources :use_cases
    resources :test_cases
    resources :requirements
    resources :issues, except: [:destroy] do
      resources :comments
    end
  end

end

app/models/issue.rb
class Issue
  include Mongoid::Document
  field :identifier, type: String
  field :title, type: String
  field :description, type: String

  has_and_belongs_to_many :labels
  belongs_to :report
  belongs_to :status
  belongs_to :project
  belongs_to :user
  embeds_many :comments

  validates :title, :identifier, :labels, presence: true

  def self.get_next_identifier(project_id)
    if Issue.where(project_id: project_id).entries.last
    	"I#{Integer(Issue.where(project_id: project_id).entries.last.identifier[/[0-9]+/])+1}"
    else
      "I1"
    end
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_labels, only: [:index, :new, :edit]
  before_action :set_statuses, only: [:index, :edit]
  before_action :require_user

  def index
    query = {project_id: params[:project_id]}
    if params[:labels] then query[:label_ids] = { "$in" => params[:labels]} end
    if params[:status] 
      if params[:status] != "All"
        query[:status] = params[:status]
      end
    end

    @issues = Issue.where(query)
  end

  def new
    @project = Project.find params[:project_id]
    @issue = Issue.new(project: @project)
  end

  def create
    @project = Project.find params[:project_id]
    identifier = Issue.get_next_identifier(project_id: @project._id)

    @issue = @project.issues.create(
      title: issues_params[:title],
      description: issues_params[:description],
      identifier: identifier,
      user_id: @project.user.id)

    @issue.status = Status.find_by(name: 'Open')
    @issue.save

    if params[:labels]
      params[:labels].each do |label|
        @issue.labels << Label.find(label)
        @issue.save
      end
      if params[:commit] == "Continue"
        format.html { redirect_to new_project_issue_path(@project) }
      else
        redirect_to project_issues_path
      end
    else
      redirect_to new_project_issue_path, notice: 'A label must be selected', alert: 'danger'
    end
  end

  def show
    @project = Project.find params[:project_id]
    @issue = @project.issues.find(params[:id])
    @comments = @issue.comments
  end

  def edit
    @project = Project.find params[:project_id]
    @issue = Project.find(params[:project_id]).issues.find(params[:id])
    @issue_labels = @issue.labels.pluck(:_id)
    @edit = true
  end

  def update
    @issue = Project.find(params[:project_id]).issues.find(params[:id])
    @issue.status = Status.find(issues_params[:status])

    if @issue.save
      if @issue.update(title: issues_params[:title], description: issues_params[:description])
        redirect_to project_issue_path
      else
        render 'edit'
      end
    end
  end

  private

    def set_labels
      @labels = Label.all.pluck(:name, :_id)
    end

    def set_statuses
      @statuses = Status.all.pluck(:name, :_id)
    end

    def issues_params
      params.require(:issue).permit(:title, :status, :description)
    end
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/views/issues/_create_edit_issue_form.html.haml
=form_for([@project, @issue]) do |f|
  .form-horizontal
    .form-group
      .field
        =f.label :title, class: 'col-sm-2 control-label'
        .col-sm-10
          =f.text_field :title, class: 'form-control'
    .form-group
      .field
        =f.label :description, class: 'col-sm-2 control-label'
        .col-sm-10
          =f.text_area :description, class: 'form-control'
    .form-group
      .field
        = label_tag 'labels', 'Labels', class: 'col-sm-2 control-label'
        .col-sm-10
          = select_tag('labels', options_for_select(@labels.to_a, @issue_labels), { :multiple => true, :class => 'form-control'})
    -if @edit
      .form-group
        .field
          =f.label :status, class: 'col-sm-2 control-label'
          .col-sm-10
            =f.select(:status, options_for_select(@statuses.to_a, @issue.status.name), {}, {class: 'form-control'})
    .form-group
      .col-sm-offset-2.col-sm-10
        .actions
          =f.submit "Save", class: 'btn btn-primary'
          = f.submit 'Continue', class: 'btn btn-primary'

app/views/issues/edit.html.haml
%h3
  ="Edit issue #{@issue.identifier}"

#edit-issue-form
  =render 'create_edit_issue_form'

= link_to 'Cancel', project_issue_path(@project, @issue)

app/views/issues/index.html.haml
- if notice
  %p{class: "alert alert-#{alert}"}= notice

.top
  %h3 Issues
  =link_to 'New Issue', new_project_issue_path, class: 'btn btn-primary pull-right'

.search
  = form_tag({:controller => 'issues', :action => 'index'}, method: 'get', class: 'form-inline')  do
    .form-group
      = select_tag :labels, options_for_select(@labels), :multiple => true, :class => 'form-control' 
    .form-group
      = select_tag :status, options_for_select(@statuses<<["All", "All"]), :class => 'form-control' 
    .form-group
      = submit_tag "Search", class: 'btn btn-default'

- if @issues.count > 0
  -@issues.each do |issue|
    //-issue.kind == 'Improvement' ? @color = 'panel-danger' : @color = 'panel-success'
    .list-item
      %h4=link_to "#{issue.identifier} #{issue.title}", project_issue_path(params[:project_id], issue.id)
      %p 
        %b Labels:
        - issue.labels.each do |l|
          = l.name
        %b Status:
        = issue.status.name
      %p=issue.description
      =link_to 'Edit', edit_project_issue_path(params[:project_id], issue.id)
- else
  %placeholder No issues.

app/views/issues/new.html.haml
- if notice
  %p{class: "alert alert-#{alert}"}= notice

%h3 New issue

#new-issue-form
  =render 'create_edit_issue_form'

app/views/issues/show.html.haml
- if notice
  %p{class: "alert alert-#{alert}"}= notice

%h3="#{@issue.identifier} #{@issue.title}"

#issue-info
  %p
    %b Labels:
    - @issue.labels.each do |l|
      = l.name
    %b Status:
    =@issue.status.name
  %p
    =@issue.description

%h4.header Comments
- @comments.each do |comment|
  .list-item
    %p=comment.date
    %p=comment.body
    %p= link_to 'Delete', project_issue_comment_path(params[:project_id], @issue.id, comment.id), method: :delete

%p
  =link_to 'Add a comment', new_project_issue_comment_path(@project, @issue)

=link_to 'Edit', edit_project_issue_path(params[:project_id], @issue.id)