config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  get 'signup' => 'users#new', as: :signup
  resources :users, except: [:index, :new]

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :projects do
    get 'new_tester' => "projects#new_tester"
    post 'new_tester' => "projects#add_tester"
    
    resources :test_runs, except: [:edit, :update] do
      get "test_run" => "test_runs#test_run", as: :test_run
      get "run_test/:identifier" => "test_runs#run_test", as: :run_test
      patch "run_test/:identifier" => "test_runs#result", as: :result
      get "new_issues/:report" => "test_runs#new_issues", as: :new_issues
      post "create_issues/:report" => "test_runs#create_issues", as: :create_issues
    end
    resources :use_cases
    resources :test_cases
    resources :requirements
    resources :issues, except: [:destroy] do
      resources :comments
    end
  end

end

app/models/project.rb
class Project
  include Mongoid::Document
  field :name, type: String
  field :description, type: String
  field :scope, type: String

  has_many :issues, dependent: :destroy
  has_many :use_cases, dependent: :destroy
  has_many :test_cases, dependent: :destroy
  has_many :requirements, dependent: :destroy
  has_many :test_runs, dependent: :destroy
  belongs_to :user
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :require_user
  
  def index
    @projects = Project.where(user_id: session[:user_id]).to_a
    user = User.find(session[:user_id])
    user.projects_testing.each do |p|
      @projects << Project.find(p)
    end
  end

  def new
    @project = Project.new
  end

  def edit
    @project = Project.find params[:id]
  end

  def show
    @project = Project.find(params[:id])
    @user = User.find(session[:user_id])
  end

  def create
    @project = Project.new(project_params)
    @project.user_id = session[:user_id]

    if @project.save
      redirect_to @project
    else
      render 'new'
    end
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
      redirect_to @project
    else
      render 'edit'
    end
  end

  def destroy
    @project = Project.find params[:id]
    @project.destroy

    redirect_to projects_path
  end

  def new_tester
    @project = Project.find(params[:project_id])
  end

  def add_tester
    @project = Project.find(params[:project_id])
    user = User.find_by(email: params[:tester][:email])

    respond_to do |format|
      if user
        if not user.projects_testing.include? @project._id
          user.projects_testing << @project._id
          user.save
          format.html { redirect_to project_new_tester_path(@project), 
            notice: "Tester added to project.",
            alert: 'success' }
        else
          format.html { redirect_to project_new_tester_path(@project), 
            notice: "Tester is already in the project.",
            alert: 'warning' }
        end
      else
        format.html { redirect_to project_new_tester_path(@project),
          notice: "Tester couldn't be added. User not found.", 
          alert: 'danger'}
      end
    end
  end

  private

    def project_params
      params.require(:project).permit(:name, :description, :scope)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_create_edit_form.html.haml
=form_for @project do |f|
  .form-horizontal
    .form-group
      .field
        =f.label :name, class: 'col-sm-2 control-label'
        .col-sm-10
          =f.text_field :name, class: 'form-control'
    .form-group
      .field
        =f.label :description, class: 'col-sm-2 control-label'
        .col-sm-10
          =f.text_area :description, class: 'form-control'
    .form-group
      .field
        =f.label :scope, class: 'col-sm-2 control-label'
        .col-sm-10
          =f.text_area :scope, class: 'form-control', rows: 5
    .form-group
      .col-sm-offset-2.col-sm-10
        .field
          =f.submit "Create project", class: 'btn btn-primary'

app/views/projects/edit.html.haml
%h3= "Edit project #{@project.title}"

#edit-project-form
  =render 'create_edit_form'

= link_to 'Back', @project

app/views/projects/index.html.haml
- @projects.each do |project|
	.col-md-4
		.project-thumbnail
			.caption
				%h3.name= link_to project.name, project_path(project)
				%p.description= project.description

app/views/projects/new.html.haml
%h3 New project

#new-project-form
  =render 'create_edit_form'

app/views/projects/new_tester.html.haml
- if notice
	%p{class: "alert alert-#{alert}"}= notice

%h3 New tester

= form_for(:tester, url: project_new_tester_path(@project)) do |f|
	.form-horizontal
		.form-group
			.field
				= f.label :email, class: 'control-label col-sm-2'
				.col-sm-6
					= f.text_field :email, placeholder: 'User email', class: 'form-control'

		.form-group
			.col-sm-offset-2.col-sm-6
				= f.submit "Add tester", class: "btn btn-primary"

app/views/projects/show.html.haml
%h3 Description
%p= @project.description

%h3 Scope
%p= @project.scope

- if @project.user_id == @user.id
	=link_to 'Add tester', project_new_tester_path(@project)
	=link_to 'Edit', edit_project_path(@project)
	=link_to 'Delete', project_path(@project), method: :delete, :data => { :confirm => 'Are you sure?' }