config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  get 'signup' => 'users#new', as: :signup
  resources :users, except: [:index, :new]

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :projects do
    get 'new_tester' => "projects#new_tester"
    post 'new_tester' => "projects#add_tester"
    
    resources :test_runs, except: [:edit, :update] do
      get "test_run" => "test_runs#test_run", as: :test_run
      get "run_test/:identifier" => "test_runs#run_test", as: :run_test
      patch "run_test/:identifier" => "test_runs#result", as: :result
      get "new_issues/:report" => "test_runs#new_issues", as: :new_issues
      post "create_issues/:report" => "test_runs#create_issues", as: :create_issues
    end
    resources :use_cases
    resources :test_cases
    resources :requirements
    resources :issues, except: [:destroy] do
      resources :comments
    end
  end

end

app/models/test_run.rb
class TestRun
  include Mongoid::Document
  field :date, type: Date
  field :tester, type: String

  has_one :summary, dependent: :destroy
  has_many :reports, dependent: :destroy
  belongs_to :project
  belongs_to :user

  validates :summary, presence: {is: true, message: "a test run must have a summary"}

  def next_test()
  	report = self.reports.find_by(result: "NR")
  	if report
	  	report.test_case["identifier"]
	  else
	  	nil
  	end
  end

  def get_report(identifier)
    TestCase.find_by(identifier: identifier).reports.find_by(test_run_id: self.id)
  end
end

app/controllers/test_runs_controller.rb
class TestRunsController < ApplicationController
  before_action :set_test_run, except: [:create, :new, :index]
  before_action :set_test_cases, only: [:new, :index]
  before_action :set_project
  before_action :require_user

  # GET /test_runs
  # GET /test_runs.json
  def index
    query = {project_id: @project._id}
    if params[:commit] == "Today" then query[:date] = Date.today end
    if params[:date]
      date = Date.parse(params[:date]) rescue nil
      if date then  query[:date] = date end
    end

    @test_runs = TestRun.where(query)
  end

  # GET /new
  def new
    @test_run = TestRun.new()
  end

  # GET /test_runs/1
  # GET /test_runs/1.json
  def show
    @tester = User.find(@test_run.tester)
  end

  # GET /test_run/:id/run_test/:identifier
  # Retrieves next test case to run.
  # If there are no more test cases to run, it redirects to the
  # test_run show page to display the result of the test run
  def test_run
    identifier = @test_run.next_test()

    respond_to do |format|
      if identifier
        format.html { redirect_to project_test_run_run_test_path(
          @project, 
          @test_run, 
          identifier: identifier)}
      else
        format.html { redirect_to project_test_run_path(@project, @test_run), 
            notice: 'Test run finished successfully.', alert: 'success' }
      end
    end
  end

  # GET /test_run/:id/run_test/:identifier
  # Run test case page displaying test case info and form to give result
  def run_test
    @test_case = TestCase.find_by(identifier: params[:identifier], project_id: @project._id)
  end

  # PATCH /test_run/:id/run_test/:identifier/:result
  # Sets the result of the test_run on the test_case :identifier
  def result
    report = @test_run.get_report(params[:identifier])
    report.update(result: params[:commit], comment: params[:comment])

    # Update the summary counts
    Summary.update_summary(@test_run.summary, params[:commit])

    if params[:commit] == "Failed"
      redirect_to project_test_run_new_issues_path(@project, @test_run, report)
    else
      redirect_to project_test_run_test_run_path(@project, @test_run)
    end
  end

  # GET /test_run/:id/new_issues/:report
  # Form to create new issues after marking a report as failed
  def new_issues
    @report = @test_run.reports.find(params[:report])
    @labels = Label.all.pluck(:name, :_id)
  end

  # POST /test_run/:id/create_issues/:report
  # Create the new issues and associate them with a report
  def create_issues
    report = @test_run.reports.find(params[:report])
    issue = report.issues.build(
      title: params[:issue][:title], 
      description: params[:issue][:description], 
      identifier: Issue.get_next_identifier(@project.id),
      project_id: @project.id,
      status_id: Status.find_by(name: 'Open').id)
    params[:issue][:labels].delete("")

    params[:issue][:labels].each do |label|
      issue.labels << Label.find(label)
    end

    if issue.save
      if params[:commit] == "Continue"
        redirect_to project_test_run_new_issues_path(@project, @test_run, report)
      else
        redirect_to project_test_run_test_run_path(@project, @test_run)
      end
    else
      redirect_to(
        project_test_run_new_issues_path(@project, @test_run, report),
        notice: "Issue couldn't be saved. Remember to add the issue's label and title.",
        alert: "danger")
    end
  end

  # POST /test_runs
  # POST /test_runs.json
  def create
    @test_run = TestRun.new(date: DateTime.now, 
      project_id: params[:project_id],
      tester: session[:user_id])

    @test_run.summary = Summary.new(
      passed: 0, 
      skipped: 0, 
      failed: 0, 
      total: 0)

    # If specific test cases where listed, then create a test run with a report object for each of the test cases
    # If all test cases where marked for run, then pull all test cases from that project and create the reports for each of them
    if params[:commit] == "Run"
      if params[:test_cases]
        params[:test_cases].each do |id|
          test_case = TestCase.find_by(_id: id, project_id: @project._id)

          report = Report.create(
            test_case_id: test_case.id,
            result: "NR", 
            comment: "", 
            test_run_id: @test_run._id)
        end
      end
    else
      test_cases = TestCase.where(project_id: @project._id)
      test_cases.each do |test_case|
        Report.create(
          test_case: test_case._id, 
          result: "NR", 
          comment: "", 
          test_run_id: @test_run._id)
      end
    end


    respond_to do |format|
      if @test_run.reports.length > 0
        @test_run.save
        format.html { redirect_to project_test_run_test_run_path(
          @project, 
          @test_run) }
      else
        format.html { redirect_to new_project_test_run_path(@project), 
          notice: 'No valid test case was given.', alert: 'danger' }
      end
    end
  end

  # DELETE /test_runs/1
  # DELETE /test_runs/1.json
  def destroy
    @test_run.destroy
    respond_to do |format|
      format.html { redirect_to project_test_runs_path(@project), 
        notice: 'Test run was successfully destroyed.', alert: 'success' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_test_run
      if params[:id]
        @test_run = TestRun.find(params[:id])
      else
        @test_run = TestRun.find(params[:test_run_id])
      end
    end

    def set_test_cases
      @tc_select = TestCase.list(params[:project_id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end
end

app/helpers/test_runs_helper.rb
module TestRunsHelper
end

app/views/test_runs/index.html.haml
- if notice
  %p{class: "alert alert-#{alert}"}= notice

.top
  %h3
    Test runs
  =link_to 'New Test Run', new_project_test_run_path(@project), class: 'btn btn-primary pull-right'

.search
  = form_tag({:controller => 'test_runs', :action => 'index'}, method: 'get', class: 'form-inline')  do
    .form-group
      = text_field_tag :date, nil, placeholder: 'yy/mm/dd', class: 'form-control'
    .form-group
      = submit_tag "Today", class: 'btn btn-default'
      = submit_tag "Search", class: 'btn btn-default'

- if @test_runs.count > 0
  - @test_runs.each do |test_run|
    .list-item
      %h4= link_to "Test run #{test_run.date}",project_test_run_path(@project, test_run)
      %p
        %b Summary:
      %p
        Total: 
        = test_run.summary.total
        Passed: 
        %span{class: 'passed'}= test_run.summary.passed
        Failed: 
        %span{class: 'failed'}= test_run.summary.failed
        Skipped: 
        %span{class: 'skipped'}= test_run.summary.skipped
      = link_to 'Delete', project_test_run_path(@project, test_run), :method => :delete, :data => { :confirm => 'Are you sure?' }
- else
  %p No test runs.

app/views/test_runs/new.html.haml
- if notice
	%p{class: "alert alert-#{alert}"}= notice
	
%h3 New test run

= form_for [@project, @test_run] do
	.form-horizontal
		.form-group
			.field
				= label_tag 'test_cases', "Test cases", class: 'col-sm-2 control-label'
				.col-sm-10
					= select_tag("test_cases", options_for_select(@tc_select), multiple: true, class: 'form-control')
		.form-group
			.col-sm-offset-2.col-sm-10
				.actions
					= submit_tag("Run all", class: 'btn btn-primary')
					= submit_tag('Run', class: 'btn btn-primary')

= link_to "Cancel", project_test_runs_path(@project)

app/views/test_runs/new_issues.html.haml
- if notice
  %p{class: "alert alert-#{alert}"}= notice

%h3= "New issue for #{@report.test_case.identifier} run"

=form_for(:issue, url: project_test_run_create_issues_path(@project, @test_run, @report)) do |f|
  .form-horizontal
    .form-group
      .field
        =f.label :title, class: 'col-sm-2 control-label'
        .col-sm-10
          =f.text_field :title, class: 'form-control'
    .form-group
      .field
        =f.label :description, class: 'col-sm-2 control-label'
        .col-sm-10
          =f.text_area :description, class: 'form-control'
    .form-group
      .field
        = f.label :labels, 'Labels', class: 'col-sm-2 control-label'
        .col-sm-10
          = f.select(:labels, options_for_select(@labels.to_a), {}, {:multiple => true, :class => 'form-control'})
    .form-group
      .col-sm-offset-2.col-sm-10
        .actions
          =f.submit "Save", class: 'btn btn-primary'
          = f.submit 'Continue', class: 'btn btn-primary'

app/views/test_runs/run_test.html.haml
%h3="#{@test_case.identifier} #{@test_case.title}"

.content
	.row
		%p
			%b Preconditions:
			= simple_format(@test_case.preconditions)
	.row
		%p
			%b Steps:
			= simple_format(@test_case.steps)
	.row
		%p
			%b Postconditions:
			= simple_format(@test_case.postconditions)

%p.instructions Follow the steps to run the test case.
%p.instructions Keep in mind that the preconditions should be satisfied before starting the test.

= form_tag project_test_run_run_test_path(@project, @test_run, identifier: @test_case.identifier), method: "patch" do
	.form-vertical
		.form-group
			= label_tag :comment, "Comments", class: 'control-label'
			= text_area_tag :comment, nil,class: 'form-control'

	.actions
		= submit_tag("Passed", class: 'btn btn-success')
		= submit_tag("Skipped", class: 'btn btn-warning')
		= submit_tag("Failed", class: 'btn btn-danger')

app/views/test_runs/show.html.haml
- if notice
	%p{class: "alert alert-#{alert}"}= notice

%h3= "Test run #{@test_run.date}"

%h4 Tester
%p
	= @tester.name
%p
	= @tester.email

%h4 Summary
%p
	%b Total:
	= @test_run.summary.total
	%b Passed:
	%span.passed= @test_run.summary.passed
	%b Failed:
	%span.failed= @test_run.summary.failed
	%b Skiped:
	%span.skipped= @test_run.summary.skipped
		
%h4.header Reports
- @test_run.reports.each do |r|
	.list-item
		%p
			%b Test Case
			- if r.test_case
				=link_to "#{r.test_case.identifier}", project_test_case_path(@project, r.test_case["_id"])
			- else
				Not Found
		%p
			%b Result:
			%span{class: "#{r.result.downcase}"}= r.result
		%p
			%b Comment:
		= r.comment
		%p
			%b Issues:
			- r.issues.each do |issue|
				= link_to "#{issue.identifier}", project_issue_path(@project, issue.id)

= link_to 'Delete', project_test_run_path(@project, @test_run), :method => :delete, :data => { :confirm => 'Are you sure?' }