config/routes.rb
Rails.application.routes.draw do
  root 'projects#index'

  get 'signup' => 'users#new', as: :signup
  resources :users, except: [:index, :new]

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :projects do
    get 'new_tester' => "projects#new_tester"
    post 'new_tester' => "projects#add_tester"
    
    resources :test_runs, except: [:edit, :update] do
      get "test_run" => "test_runs#test_run", as: :test_run
      get "run_test/:identifier" => "test_runs#run_test", as: :run_test
      patch "run_test/:identifier" => "test_runs#result", as: :result
      get "new_issues/:report" => "test_runs#new_issues", as: :new_issues
      post "create_issues/:report" => "test_runs#create_issues", as: :create_issues
    end
    resources :use_cases
    resources :test_cases
    resources :requirements
    resources :issues, except: [:destroy] do
      resources :comments
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Utrim</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic|Open+Sans+Condensed:300,300italic,700' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
<header>
	<h1 class="site-header">UTRIM</h1>
	<% if user = current_user %>
		<nav class="nav">
			<ul>
				<li><%= link_to 'Projects', projects_url, class: "pull-left" %></li>
				<div class="pull-right">
					<li><%= link_to 'Profile', edit_user_path(current_user.id) %></li>
					<li><%= link_to 'Logout', logout_path, method: 'delete' %></li>
				</div>
			</ul>
		</nav>
		<% if @project %>
			<h2 class="page-header"><%= @project.name %></h2>
		<% else %>
			<h2 class="page-header">
				Projects
				<%=link_to 'New Project', new_project_path, class: 'btn btn-primary pull-right'%>
			</h2>
		<% end %>
	<% end %>
</header>

<div class="row">
<% if @menu %>
<aside class="menu col-md-3">
	<% @menu.each do |link| %>
		<% if controller.controller_name == link[:controller] %>
			<li><%= link_to link[:name], link[:path], class: 'active' %></li>
		<% else %>
			<li><%= link_to link[:name], link[:path]%></li>
		<% end %>
	<% end %>
</aside>
<% end %>

<% if @project %>
<section class="main col-md-8">
<% else %>
<section class="main">
<% end %>
	<%= yield %>
</section>
</div>

<footer class="row">
	<div class="authors">
		<div class="author">
			<span class="name">Denisse Lara</span>
			<a href="https://github.com/huesitos"><%=image_tag("github.svg")%></a>
		</div>
		<div class="author">
			<span class="name">Teodoro Alcantara</span>
			<a href="https://github.com/marti700"><%=image_tag("github.svg")%></a>
		</div>
		</div>
</footer>

</body>
</html>